### ISSUE TITLE
cookies not found: Firefox (cookie manager) versus Chrome (native cookie tool)

### ISSUE THREAD

**Issue by mahgonzales** [Rob--W/cookie-manager#50]
I opened the cookie manager on a website, and no cookies were found. The browser used was Firefox. Then I tested it in Chrome, using the native cookie tool in use and more than 20 cookies were displayed on the website. How is it possible? I know that this page even has added Youtube videos, reCaptcha. Which tool is correct?

Best Regards,
Marcella M.

**Comment by Rob--W** [comment]
Are you using the cookie manager to show all cookies for the tab? That only shows the cookies related to the website. Third-party cookies are not shown (unless first-party isolation or dynamic first-party isolation is enabled, because in that case third-party cookies can be associated with specific websites).

The Cookie Manager can be used to view all cookies if you don't specify any query.

If you are already not specifying any query, and still see differences between Firefox and Chrome, then that could also be caused by differences in browser settings. For example, if you block all third-party cookies, then cookies won't appear at all.

**Comment by mahgonzales** [comment]
Thanks for answering me. But. you're right, in fact the site I'm analyzing doesn't have cookies at all, only third-party cookies. Today this is my biggest problem, identifying third-party cookies to create Privacy Policies by mentioning a glossary of third-party cookies that may contain on our pages. Do you know of a tool that I can more safely determine third-party cookies?

Best regards,
Marcella

**Comment by Rob--W** [comment]
> Do you know of a tool that I can more safely determine third-party cookies?

You could use containers for that (https://support.mozilla.org/en-US/kb/containers). Create a new container and open the website that you'd like to analyze in that container. You can then use this extension to view all cookies within that container.

Another way to identify the right cookies is to enable dynamic first-party isolation that I mentioned before (also known as Total Cookie Protection - https://blog.mozilla.org/en/products/firefox/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/ ). With this mechanism, all third-party cookies will be keyed by the top-level website. Because of the clear link between the (third-party) cookie and the website, the extension can reliably show the relevant third-party cookies.

**Comment by mahgonzales** [comment]
Really appreciate your help. 

Thanks!
